-- Ato no anasiana ny script raha te hanana base de donnée operationnel
create table tusers (
  id INT auto_increment primary key,
  login VARCHAR(255) not null,
  password VARCHAR(255) not null,
  salt VARCHAR(255) not null,
  firstname VARCHAR(255) not null,
  lastname VARCHAR(255) not null,
  profile INT not null,
  mail VARCHAR(255) not null,
  phone VARCHAR(255) not null,
  mobile VARCHAR(255) not null,
  fax VARCHAR(255) not null,
  `function` VARCHAR(255) not null,
  company INT not null,
  address1 VARCHAR(255) not null,
  address2 VARCHAR(255) not null,
  zip VARCHAR(255) not null,
  city VARCHAR(255) not null,
  custom1 VARCHAR(255) not null,
  custom2 VARCHAR(255) not null,
  disable INT not null,
  chgpwd INT not null,
  last_login DATETIME not null,
  last_pwd_chg DATE not null,
  auth_attempt INT not null,
  ip VARCHAR(255) not null,
  skin VARCHAR(255) not null,
  default_ticket_state VARCHAR(255) not null,
  dashboard_ticket_order VARCHAR(255) not null,
  limit_ticket_number INT not null,
  limit_ticket_days INT not null,
  limit_ticket_date_start DATE not null,
  language VARCHAR(255) not null default 'fr_FR',
  ldap_guid VARCHAR(255) not null,
  ldap_sid VARCHAR(255) not null,
  azure_ad_id VARCHAR(255) not null,
  planning_color VARCHAR(255) not null
);

-- Insertion de l'utilisateur 1
INSERT INTO tusers (login, password, salt, firstname, lastname, profile, mail, phone, mobile, fax, 'function', company, address1, address2, zip, city, custom1, custom2, disable, chgpwd, last_login, last_pwd_chg, auth_attempt, ip, skin, default_ticket_state, dashboard_ticket_order, limit_ticket_number, limit_ticket_days, limit_ticket_date_start, language, ldap_guid, ldap_sid, azure_ad_id, planning_color)
VALUES ('utilisateur1', 'motdepasse1', 'sel1', 'John', 'Doe', 1, 'john.doe@email.com', '123-456-7890', '987-654-3210', '123-123-123', 'Manager', 1, '123 Street Name', 'Apt 4B', '12345', 'Cityville', 'Custom1', 'Custom2', 0, 1, '2023-10-19 12:00:00', '2023-10-19', 0, '192.168.1.1', 'light', 'open', 'order', 100, 30, '2023-10-19', 'fr_FR', 'ldap_guid1', 'ldap_sid1', 'azure_ad_id1', 'blue');

-- Insertion de l'utilisateur 2
insert
	into
	tusers (login,
	password,
	salt,
	firstname,
	lastname,
	profile,
	mail,
	phone,
	mobile,
	fax,
	`function`,
	company,
	address1,
	address2,
	zip,
	city,
	custom1,
	custom2,
	disable,
	chgpwd,
	last_login,
	last_pwd_chg,
	auth_attempt,
	ip,
	skin,
	default_ticket_state,
	dashboard_ticket_order,
	limit_ticket_number,
	limit_ticket_days,
	limit_ticket_date_start,
	language,
	ldap_guid,
	ldap_sid,
	azure_ad_id,
	planning_color)
values ('utilisateur2',
'motdepasse2',
'sel2',
'Jane',
'Smith',
2,
'jane.smith@email.com',
'987-654-3211',
'123-456-7891',
'456-456-456',
'Developer',
2,
'456 Street Road',
'Apt 2A',
'54321',
'Townsville',
'CustomA',
'CustomB',
1,
1,
'2023-10-18 14:30:00',
'2023-10-18',
0,
'192.168.1.2',
'dark',
'inprogress',
'priority',
50,
15,
'2023-10-18',
'en_US',
'ldap_guid2',
'ldap_sid2',
'azure_ad_id2',
'red');

